version: "3.9"

services:
  github-app:
    build: .
    container_name: "githup-app"
    environment:
      - GITHUB_APP_ID=${GITHUB_APP_ID}
      - GITHUB_APP_PRIVATE_KEY=${GITHUB_APP_PRIVATE_KEY}
    ports:
      - ${SETUP_PORT}:8888