[build]
    functions = "netlify/functions"

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200

[dev]
    port = 8000
    command = "node --env-file .env scripts/dev-server.js"
    # serve static files
    publish = "public"