# Settings for the [build] key are global and are applied to
# all deploy contexts unless overridden by a context-specific setting.
[build]

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200

[dev]
    port = 8000
    publish = "public"
    command = "node dev/server.js"

[functions]
    node_bundler = "esbuild"