name: Release
"on":
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.PRETTIER_APP_ID }}
          private-key: ${{ secrets.PRETTIER_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: ${{ github.head_ref }}
          # Make sure the value of GITHUB_TOKEN will not be persisted in repo's config
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm
      - run: npm run format
      - run: |
          git commit -am 'style: prettier' && git push || echo "No changes to commit"
